import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useSession } from 'next-auth/react'
import { useState, useEffect } from 'react'
import musicData from '../../../heardle/muisc.json';


const inter = Inter({ subsets: ['latin'] })

const baseUrl = "https://api.musixmatch.com/ws/1.1/"
const eststs = `artist.search?q_artist=neighborhood&page_size=5&apikey=${process.env.MUSIXMATCH_CLIENT_ID}`

const apiKey = process.env.MUSIXMATCH_CLIENT_ID

export default function Home() {
//   for (let i = 0; i < data.length; i++){

// console.log(data[i].Track_Name + ", by " + data[i].Artist_Name + "");
// }
  //  access session information
  const { data: session } = useSession();
  //  console.log(session.accessToken);
  const [topArtists, setTopArtists] = useState([]);


  // useEffect(() => {
  //   if (session && session.accessToken) {

  //     const fetchData = async () => {
  //       const response = await fetch("https://api.spotify.com/v1/me/top/artists?time_range=medium_term&limit=5&offset=0", {
  //         method: "GET", headers: { Authorization: `Bearer ${session.accessToken}` }
  //       });
  //       const json = await response.json();
  //       setTopArtists(json.items);
  //     };
  //     fetchData();
  //   }
  // }, [session])

  // console.log(`test ${process.env.SPOTIFY_CILLENT_ID}`)
  useEffect(() => {
    if (session && session.accessToken) {

      const fetchMusic = async () => {
        //TODO: Figure this out wtf
        const response = await fetch(`https://cors-anywhere.herokuapp.com/http://api.musixmatch.com/ws/1.1/matcher.track.get?q_track=${musicData[455].Track_Name}&q_artist=${musicData[455].Artist_Name}&apikey=4290ff500d68899a2ef375d7d2e88f63`, {
          method: "GET",
        }
        );

        const json = await response.json();
        console.log(json.message.body.track);
      };

      const fetchData = async () => {
        const response = await fetch("https://api.spotify.com/v1/me/top/artists?time_range=medium_term&limit=5&offset=0", {
          method: "GET", headers: { Authorization: `Bearer ${session.accessToken}` }
        });
        const json = await response.json();
        setTopArtists(json.items);
      };
      // fetchData();
      fetchMusic();
    }
  }, [session]);




  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={`${styles.main} ${inter.className}`}>
        {/* hello {session.user.name} */}
        <div>
          top artists:
          {topArtists.map((item) => (
            <div key={item.id}>{item.name}</div>
          ))}
        </div>
      </main>
    </>
  )
}

async function getProfile(token, setId) {
  const profile = await fetchProfile(token);
  setId(profile.id)
  return {
    id: profile.id,
    email: profile.email,
    uri: profile.uri,
  }
}

async function getArtists(token, setArtists) {
  const artists = await fetchTopArtists(token);
  // setArtists(artists);
  console.log(artists.items);
  return artists.items;
}

async function fetchTopArtists(token) {
  const result = await fetch("https://api.spotify.com/v1/me/top/artists?time_range=medium_term&limit=5&offset=0", {
    method: "GET", headers: { Authorization: `Bearer ${token}` }
  });
  // console.log(result.object);
  return await result.json();
}


async function fetchProfile(token) {
  const result = await fetch("https://api.spotify.com/v1/me", {
    method: "GET", headers: { Authorization: `Bearer ${token}` }
  });
  return await result.json();
}
